name: CI

# Trigger the workflow on push or pull request
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - devel
          - '4.14'
          - '4.13'
          - '4.12'
          - '4.11'
          - '4.10'

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v2
      - uses: stertooy/install-pkg@main
        with:
          packages: 'io json'
      - uses: gap-actions/run-pkg-tests@v4
