name: setup-gap-test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  test:
    name: "Test package with GAP-${{ matrix.gap-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-24.04", "ubuntu-24.04-arm", "windows-2025", "windows-11-arm", "macos-15", "macos-15-large" ]
        gap-version: [ "latest", "master", "4.15.0-beta1", "4.14", "4.13", "4.12", "4.11", "4.10" ]
        
    steps:
    
      - name: "Setup Cygwin"
        uses: gap-actions/setup-cygwin@v2
        if: ${{ runner.os == 'Windows' }}
        
      - name: "Checkout package"
        uses: actions/checkout@v5

      - name: "Setup GAP"
        uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}

      - name: "Build package"
        uses: gap-actions/build-pkg@main
          
      - name: "Run package tests"
        uses: gap-actions/run-pkg-tests@main

      - name: "Build package documentation"
        uses: gap-actions/build-pkg-docs@v2
        if: ${{ runner.os == 'Linux' }}
        with:
          use-latex: 'true'
